/*
 * Browser-only MLS integration.
 *
 * This module deliberately does not know about the backend transport. The
 * caller may send `welcome`, `proposal`, `commit`, and `ciphertext` values to
 * the relay, but the opaque group state and all private keys remain in this
 * browser/client boundary.
 */

export const MLS_CIPHERSUITE = 'MLS_128_DHKEMX25519_AES128GCM_SHA256_Ed25519' as const;

export type MlsBytes = Uint8Array;

export type MlsTransportMessage =
  | { type: 'welcome'; groupId: string; bytes: MlsBytes }
  | { type: 'proposal'; groupId: string; bytes: MlsBytes }
  | { type: 'commit'; groupId: string; bytes: MlsBytes }
  | { type: 'ciphertext'; groupId: string; bytes: MlsBytes };

export type MlsClientOptions = {
  /** Public credential material. Private signing state is generated by MLS. */
  credential: MlsBytes;
  /** Restores opaque state previously returned by exportState(). */
  state?: MlsBytes;
};

type OpenMlsModule = {
  default?: () => Promise<unknown> | unknown;
  init?: () => Promise<unknown> | unknown;
  Client?: new (...args: unknown[]) => OpenMlsInstance;
  MlsClient?: new (...args: unknown[]) => OpenMlsInstance;
  WasmClient?: new (...args: unknown[]) => OpenMlsInstance;
};

type OpenMlsInstance = Record<string, unknown>;

const MODULE_NAME = '@openmls/wasm';

function asBytes(value: unknown, name: string): MlsBytes {
  if (value instanceof Uint8Array) return value;
  if (value instanceof ArrayBuffer) return new Uint8Array(value);
  if (ArrayBuffer.isView(value)) {
    return new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
  }
  throw new Error(`OpenMLS returned an invalid ${name}`);
}

function requiredMethod(instance: OpenMlsInstance, names: string[]): (...args: unknown[]) => unknown {
  for (const name of names) {
    const method = instance[name];
    if (typeof method === 'function') return method.bind(instance) as (...args: unknown[]) => unknown;
  }
  throw new Error(`OpenMLS WASM binding does not expose ${names.join(' or ')}`);
}

async function loadBinding(): Promise<OpenMlsModule> {
  if (typeof window === 'undefined') {
    throw new Error('MLS is only available in a browser context');
  }

  const module = (await import(MODULE_NAME)) as OpenMlsModule;
  const initializer = module.default ?? module.init;
  if (initializer) await initializer();
  return module;
}

function createBinding(module: OpenMlsModule, options: MlsClientOptions): OpenMlsInstance {
  const Constructor = module.MlsClient ?? module.WasmClient ?? module.Client;
  if (!Constructor) throw new Error('OpenMLS WASM client constructor is unavailable');

  return new Constructor(options.credential, MLS_CIPHERSUITE, options.state ?? null);
}

export class MlsClient {
  private constructor(
    private readonly binding: OpenMlsInstance,
    readonly groupId: string,
  ) {}

  static async create(groupId: string, options: MlsClientOptions): Promise<MlsClient> {
    if (!groupId) throw new Error('groupId is required');
    if (!(options.credential instanceof Uint8Array)) throw new Error('credential must be Uint8Array');

    const module = await loadBinding();
    return new MlsClient(createBinding(module, options), groupId);
  }

  async createGroup(): Promise<MlsTransportMessage[]> {
    const create = requiredMethod(this.binding, ['createGroup', 'create_group']);
    const result = await create(this.groupId);
    return normalizeMessages(result, this.groupId);
  }

  async join(welcome: MlsBytes): Promise<void> {
    const join = requiredMethod(this.binding, ['joinGroup', 'join_group', 'join']);
    await join(welcome);
  }

  async addMember(externalCredential: MlsBytes): Promise<MlsTransportMessage[]> {
    const add = requiredMethod(this.binding, ['addMember', 'add_member']);
    return normalizeMessages(await add(externalCredential), this.groupId);
  }

  async encrypt(plaintext: MlsBytes, authenticatedData: MlsBytes = new Uint8Array()): Promise<MlsBytes> {
    const encrypt = requiredMethod(this.binding, ['encryptMessage', 'encrypt_message', 'encrypt']);
    return asBytes(await encrypt(plaintext, authenticatedData), 'ciphertext');
  }

  async decrypt(ciphertext: MlsBytes, authenticatedData: MlsBytes = new Uint8Array()): Promise<MlsBytes> {
    const decrypt = requiredMethod(this.binding, ['decryptMessage', 'decrypt_message', 'decrypt']);
    return asBytes(await decrypt(ciphertext, authenticatedData), 'plaintext');
  }

  /** Returns opaque local state. Never pass this value to a backend or relay. */
  async exportState(): Promise<MlsBytes> {
    const exportState = requiredMethod(this.binding, ['exportState', 'export_state', 'serialize']);
    return asBytes(await exportState(), 'group state');
  }

  async applyCommit(commit: MlsBytes): Promise<void> {
    const apply = requiredMethod(this.binding, ['applyCommit', 'apply_commit', 'processCommit', 'process_commit']);
    await apply(commit);
  }

  close(): void {
    const free = this.binding.free;
    if (typeof free === 'function') (free as () => void).call(this.binding);
  }
}

function normalizeMessages(value: unknown, groupId: string): MlsTransportMessage[] {
  if (!value) return [];
  const values = Array.isArray(value) ? value : [value];

  return values.map((entry) => {
    const bytes = asBytes(entry, 'protocol message');
    return { type: 'commit', groupId, bytes };
  });
}
